language: java
install: mvn clean install
jdk:
  - oraclejdk11
notifications:
  recipients:
    - cadox8@gmail.com
  on_success: never # default: change
  on_failure: always # default: always

webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=123abc4d

branches:
  only:
    - gh-pages
    - /.*/

after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
